# Generated by Django 5.2 on 2025-11-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emotion", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emotionstreamentry",
            new_name="emotion_emo_session_b325e5_idx",
            old_name="emotion_emo_session_f21435_idx",
        ),
    ]
